defaults:
    - base_configuration
    - vqvae: base_vqvae
    - pixelcnn: base_pixelcnn
    - scoring_network: base_scoring_network
    - trainer: vqvae
    - dataset: pixelcnn # set to pixelcnn for the default inference complete mode
    - projection: base_projection
    - live: simulation
    - _self_
    - override hydra/hydra_logging: none
    - override hydra/job_logging: none

vqvae:
    checkpoint_path: "/home/laksh/crowdsurfer_ws/src/CrowdSurfer_wheelchair_livox/src/CrowdSurfer/checkpoints/vqvae_best_64_4.bin"
pixelcnn:
    checkpoint_path: "/home/laksh/crowdsurfer_ws/src/CrowdSurfer_wheelchair_livox/src/CrowdSurfer/checkpoints/pixelcnn_best_64_4.bin"
mode: LIVE
